### ISSUE TITLE
CircularReveal animation is revealing under the TabLayout

### ISSUE THREAD

**Issue by JovieBrett** [coyarzun89/FabTransitionActivity#12]
The reveal circle animation of FAB is under my TabLayout, is there a way to fix it by playing the motion above them?

![screenshot_20160304-031808](https://cloud.githubusercontent.com/assets/5206764/13506241/227bc232-e1b8-11e5-8eff-1c8f96635750.png)

**Comment by nienlm-hhtv** [comment]
you should place the sheet layout outside the CoordinatorLayout and set the width and height to fill parent

**Comment by DarkNormal** [comment]
@JovieBrett did you solve this issue?

**Comment by JovieBrett** [comment]
@nienlm-hhtv @DarkNormal but it made the whole screen white so I move it back inside the CoordinatorLayout and  tried to set width and height to fill_parent, it still doesn't work.

**Comment by DarkNormal** [comment]
@JovieBrett do you have your code available on Github to look at? I had a similar issues ([see here](https://github.com/coyarzun89/FabTransitionActivity/issues/6)) but my original fix was a dirty hack so I wouldn't recommend it, although @simongiesen suggestion did help me come up with a better solution afterwards (Moving the SheetLayout out of a fragment layout and into the Activity layout)

**Comment by JovieBrett** [comment]
@DarkNormal nope but I will make it available later.

**Comment by nienlm-hhtv** [comment]
@JovieBrett anw you should'n place your sheet inside CoordinatorLayout

**Comment by JovieBrett** [comment]
@DarkNormal Temporary fix: adding app:elevation="0dp" to the toolbar.

**Comment by JovieBrett** [comment]
@DarkNormal @nienlm-hhtv 
Fixed it by making <RelativeLayout> the parent attribute on my xml layout, let's say:

```
<RelativeLayout>
<SheetLayout>
</SheetLayout>
<android.support.design.widget.CoordinatorLayout>
<android.support.design.widget.FloatingActionButton>
</android.support.design.widget.FloatingActionButton>
</android.support.design.widget.CoordinatorLayout>
</RelativeLayout>
```

As @nienlm-hhtv stated, SheetLayout should be outside of CoordinatorLayout. Cheers!

**Comment by dharavp** [comment]
```
<RelativeLayout>
<android.support.design.widget.CoordinatorLayout>
<android.support.design.widget.FloatingActionButton>
</android.support.design.widget.FloatingActionButton>
</android.support.design.widget.CoordinatorLayout>
<SheetLayout>
</SheetLayout>
</RelativeLayout>
```

@JovieBrett SheetLayout should be outside of coordinateLayout and also it should be overlap the coordinate Layout.
