### ISSUE TITLE
Error:Failed to resolve CircularReveal

### ISSUE THREAD

**Issue by JonathanImperato** [coyarzun89/FabTransitionActivity#2]
Error:Failed to resolve: com.github.ozodrukh:CircularReveal:1.1.1
<a href="openFile:C:/Users/Imperato/Documents/jo/myapp/beta/ServiceNotes/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

What's wrong?

**Comment by jeancsanchez** [comment]
Don't forget it

``` gradle
repositories {
         mavenCentral()
         maven {
            url "https://jitpack.io"
        }
}
```
