### ISSUE TITLE
Manifest merge failed android:allowBackup="false" 

### ISSUE THREAD

**Issue by RobertoAlvarezCeballos** [coyarzun89/FabTransitionActivity#4]
I think there is a problem with the library and one of the properties in the manifest. I'm getting the following error:

manifest merge failed android:allowBackup="false" 

This is a known issue, but in any case I don't think the library should include this property as it's forcing the app to use it as well. 

https://code.google.com/p/android/issues/detail?id=70073

**Comment by coyarzun89** [comment]
I will remove that property in the next version. Thanks!
