### ISSUE TITLE
Consider Prefixing @+id

### ISSUE THREAD

**Issue by fnk0** [coyarzun89/FabTransitionActivity#5]
Inside SheetLayout you have this line of code:

``` java
mFabExpandLayout = ((LinearLayout) findViewById(R.id.container));
```

`R.id.container` is a very common ID to assign... would be better if you used `R.id.ft_container`, the same for all your other ID's... That would cause less problems.

It took me a little bit to figure out why my app was crashing when trying to use the library, I finally figured it out and prefixed my code. Anyways... prefixing your ID's or using more uncommons ID's would be a good enhancement in the library to avoid crashes on apps implementing the library

**Comment by coyarzun89** [comment]
Thanks for the advice. I will do the change in the next version.
