### ISSUE TITLE
FabTransition from Fragment

### ISSUE THREAD

**Issue by DarkNormal** [coyarzun89/FabTransitionActivity#6]
I have a FloatingActionButton inside a Fragment, and I have your solution almost working fully. 
When I click the FAB, The SheetLayout expands correctly, but it doesn't overlap over the Toolbar/ActionBar as this is in the Activity containing the Fragment. I've tried swapping around some elements etc. but I haven't figured it out yet. 
I have attached screenshots to explain.

Any help or tips is appreciated :)

![screenshot_2016-01-07-14-43-18](https://cloud.githubusercontent.com/assets/4855895/12173865/2ec6e424-b551-11e5-982d-d22c4684c261.png)
![screenshot_2016-01-07-14-43-13](https://cloud.githubusercontent.com/assets/4855895/12173864/2e9e64d6-b551-11e5-9cd9-6c947963dc55.png)

**Comment by simongiesen** [comment]
yep, it doesn't work! Please mark it as a bug!
Workaround: Place sheetLayout in your main Activity and use an event bus to inform that Activity that one has tapped on the fab button ...

**Comment by DarkNormal** [comment]
My workaround was to use an animation to fade out the toolbar/sliding tab strip that I have. When the FAB is clicked, I animate the LinearLayout containing the Toolbar to fade to 0 alpha, at a duration of 250 which is about the length of the FAB Transition. I also set the Toolbar visibility to gone 250 after the alpha animation using a Runnable, seems to work for me anyway. I tried putting the SheetLayout in the Activity but I couldn't figure it out with multiple fragments in the same Activity & Pager.

```
FloatingActionButton addEvent = (FloatingActionButton) v.findViewById(R.id.addEvent_Button);
    addEvent.setOnClickListener(new View.OnClickListener() {
        @Override
        public void onClick(View v) {
            mSheetLayout.expandFab();
            toolbar = (LinearLayout) getActivity().findViewById(R.id.main_toolbar_holder);
            toolbar.animate()
                    .alpha(0.0f)
                    .setDuration(250);
            Handler handler = new Handler();
            handler.postDelayed(new Runnable() {
                @Override
                public void run() {
                    toolbar.setVisibility(View.GONE);
                }
            },250);
        }
    });
```

**Comment by simongiesen** [comment]
PS: here is a more easier approach.
1. Put the com.github.fabtransitionactivity.SheetLayout in your (Main) Activity.
2. In your fragment in onViewCreated do 
   mSheetLayout = (SheetLayout) view.getRootView().findViewById(R.id.bottom_sheet);

Like this it works, the sheet layout will be always on top:

mFab.setOnClickListener(new View.OnClickListener() {
            public void onClick(View v) {

```
            mSheetLayout.expandFab();
        }
    });
```

**Comment by DarkNormal** [comment]
@simongiesen Hmm I tried that but the SheetLayout covers my Fragment so I can't see the FAB or anything, thought it could've been match_parent for it but changing that to wrap_content doesn't work either. Do you have it implemented in a project I could look at?
