### ISSUE TITLE
Dependency error

### ISSUE THREAD

**Issue by vbeskrovnov** [coyarzun89/FabTransitionActivity#8]
Hello, when i add your library to build.gradle, i have error:
Failed to resolve: com.github.ozodrukh:CircularReveal:1.1.1

I think, it because the version of this library is outdated.

**Comment by DarkNormal** [comment]
At the bottom of the README file it says "This library use following libraries." and lists CircularReveal, a separate library which you will also need to include in your build.gradle file.

You can find the CircularReveal library at [this repositiory](https://github.com/ozodrukh/CircularReveal).

**Comment by vbeskrovnov** [comment]
Ok, thank you very much

**Comment by coyarzun89** [comment]
Sorry, you just need to add these line to your build.gradle file:

```
repositories {
    mavenCentral()
    maven {
        url "https://jitpack.io"
    }
}
```
